### ISSUE TITLE
GetOriginalType parameter error: Value cannot be null

### ISSUE THREAD

**Issue by alexanddercrb** [joseftw/EPiServer-ContentData-ToJson#34]
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ArgumentNullException: Value cannot be null.
Parameter name: subject
   at EPiServer.RuntimeModelExtensions.GetOriginalType(Object subject)
   at JOS.ContentSerializer.Internal.PropertyResolver.GetProperties(IContentData contentData)
   at JOS.ContentSerializer.Internal.PropertyManager.GetStructuredData(IContentData contentData, IContentSerializerSettings settings)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at JOS.ContentSerializer.Internal.PropertyManager.GetStructuredData(IContentData contentData, IContentSerializerSettings settings)
   at JOS.ContentSerializer.Internal.JsonContentSerializer.Serialize(IContentData contentData)
   at JOS.ContentSerializer.IContentDataExtensions.ToJson(IContentData contentData)

**Comment by joseftw** [comment]
Need more info.....

**Comment by alexanddercrb** [comment]
Hi. I was still checking around this. After installing the plugin from NuGet I simply tried to assign the resulting json to a string variable and had this error. Not sure if an unsupported type might cause this. I also tried a page with no blocks in order to avoid complexity.
That's the stack trace I have starting from my controller call.


Here is what I have in my controller:

_public override ActionResult Index(LimitedPage currentPage)
        {
            string test = currentPage.ToJson();
            return View(currentPage);
        }_

Versions:
EpiServer 11.20.6.0
EpiServer UI 11.35.2.0

**Comment by joseftw** [comment]
Could you post your LimitedPage as well?

**Comment by alexanddercrb** [comment]
Sorry but I can't.
Limited page is 5 steps away from PageData type (inheritage tree) and it contains properties of type like:
- ContentArea
- ContentReference
- XhtmlString
- Page types and block types (inheriting from BlockData or PageData)
- Types that are not inheriting ContentData (maybe here is the problem)

Example of property that does not inherit ContentData:
_public class StickyNavigation
    {
        public Dictionary<string, string> NavigationItems { get; set; }
    }_

**Comment by joseftw** [comment]
5 steps you say...I would assume that this call could be a problem then. `GetOriginalType`

If you can setup some kind of repro I can have a look.

**Comment by joseftw** [comment]
Try using the ignore attribute on properties that could be problematic and see if that solves the problem. Then we can take it from there.

**Comment by alexanddercrb** [comment]
I don't understand what's wrong here. I ignored every single property and it still failing.

**Comment by alexanddercrb** [comment]
Here is what I found so far:
- On first call, GetStructuredData is called with a not null contentData parameter
- There is a second call on GetStructuredData where contentData parameter is null. This call comes from BlockDataPropertyHandler (line 31)
- The PropertyInfo parameter points to an ignored block. The block looks like this:

```
public class AnchorWebControl : WebControlBase
    {
        [CultureSpecific]
        [Display(
            Name = "Link text",
            Description = "Text to display",
            Order = 100)]
        [StringLength(35)]
        [NoPlaceholder]
        public virtual string AnchorText { get; set; }

        [BackingType(typeof(PropertyUrl))]
        [CultureSpecific]
        [Display(
            Name = "URL",
            Description = "URL, page, media, email of the link",
            Order = 101)]
        public virtual Url AnchorUrl { get; set; }

        public bool HasLink => AnchorUrl != null && !AnchorUrl.IsEmpty();
    }
```

```
public abstract class WebControlBase : BlockData
    {
        private string _pageUrl;

        /// <summary>
        /// Gets the page URL.
        /// </summary>
        [Ignore]
        public string PageUrl
        {
            get { return _pageUrl = _pageUrl ?? UrlHelpers.CurrentPageUrl; }
        }

        public void OverridePageUrl(string pageUrl)
        {
            _pageUrl = pageUrl;
        }
    }
```

**Comment by alexanddercrb** [comment]
I think I understand why this is happening and how to reproduce it. To be more specific I will follow my structure that fails.

1. Create a page inheriting from PageData. Let's name it Page1.
2. Create a block inheriting from BlockData. Let's call it BlockF.
3. Add the block to the Page1 model. (public virtual BlockF TestBlock {get; set;})
4. Create a new page inheriting from Page1. I'll call it Page2.
5. On Page2 model override the TestBlock property, which is a BlockF type, and mark it with [Ignore] decorator. 
6. Create a new page inheriting from Page2 and try to convert it to json.

In this case, the TestBlock property will always be null. While looping through properties in PropertyManager.cs, the value will be always null (line 53). This is the starting point of the problem.

**Comment by joseftw** [comment]
Thanks, will try to reproduce when I have time! :)
